# Generated by Django 4.2.1 on 2023-06-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_remove_linguagem_projetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAptidao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='ProfessorResponsavel',
            new_name='professor',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='criador',
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portofolio.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aptidao',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portofolio.tipoaptidao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portofolio.tipoprojeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portofolio.tipotecnologia'),
            preserve_default=False,
        ),
    ]
