# Generated by Django 4.2.1 on 2023-06-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_remove_professor_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interesses',
        ),
    ]
