# Generated by Django 4.2.2 on 2023-06-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_delete_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.cadeira'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='portofolio.tecnologia'),
        ),
    ]
