# Generated by Django 4.2.2 on 2023-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_projeto_cadeira_projeto_tecnologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='resumo_competencias',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='resumo_estudos',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='resumo_sobre',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='pokemon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(default='dwawd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='resumo',
            field=models.TextField(default='dwadw'),
            preserve_default=False,
        ),
    ]
