# Generated by Django 4.2.1 on 2023-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0008_alter_projeto_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='pokemon',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
