# Generated by Django 4.2.1 on 2023-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_alter_projeto_pokemon'),
    ]
