# Generated by Django 4.2.1 on 2023-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0012_linguagem_acronimo_linguagem_ano_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='aptidao',
            name='cadeiras',
            field=models.ManyToManyField(blank=True, null=True, to='portofolio.cadeira'),
        ),
        migrations.AddField(
            model_name='aptidao',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, to='portofolio.projeto'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(default='wda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(to='portofolio.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='link_lusofona',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pessoas',
            field=models.ManyToManyField(to='portofolio.pessoa'),
        ),
        migrations.AddField(
            model_name='universidade',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/universidade/'),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='imagem_exemplo',
            field=models.ImageField(blank=True, null=True, upload_to='snippets/'),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/linguagens/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pokemon',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
