# Generated by Django 4.2.1 on 2023-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0013_remove_cadeira_professor_remove_projeto_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/escola/'),
        ),
        migrations.AddField(
            model_name='universidade',
            name='fim',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='universidade',
            name='inicio',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
