# Generated by Django 4.2.1 on 2023-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0015_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='acronimo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
