# Generated by Django 4.2.1 on 2023-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0016_tecnologia_acronimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='criador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
