# Generated by Django 4.2.1 on 2023-06-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0017_remove_tecnologia_pessoa_tecnologia_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='linguagens',
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_relatorio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orientadores',
            field=models.ManyToManyField(to='portofolio.professor'),
        ),
    ]
