# Generated by Django 4.2.1 on 2023-06-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0018_remove_projeto_imagem_remove_projeto_linguagens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='resumo',
        ),
    ]
