# Generated by Django 4.2.1 on 2023-06-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0020_alter_projeto_orientadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, to='portofolio.linguagem'),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/tecnologias/'),
        ),
    ]
