# Generated by Django 4.2.1 on 2023-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0021_tecnologia_linguagens_tecnologia_logotipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoColetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
